spring:
  application:
    name: PartyHubBackend
  datasource:
    url: jdbc:postgresql://localhost:5432/PartyHubDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    enabled: false


